name: Compiler

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: GDLauncher
    - run: yarn
    - run: yarn dev
    - run: yarn start
