name: yarn
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn --version
      - run: eslint -v
      - run: webpack --version
      - run: python3 -V
