name: yarn
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - sudo apt install curl
      - sudo apt install yarn
      - yarn --version 
